name: Terraform

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: us-east-1

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: terraform
        run: |
          terraform plan -input=false \
            -var aws_region=${{ env.AWS_REGION }} \
            -var db_username=${{ secrets.DB_USERNAME }} \
            -var db_password=${{ secrets.DB_PASSWORD }}

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        working-directory: terraform
        run: |
          terraform apply -input=false -auto-approve \
            -var aws_region=${{ env.AWS_REGION }} \
            -var db_username=${{ secrets.DB_USERNAME }} \
            -var db_password=${{ secrets.DB_PASSWORD }}
